name: presto_mobile
description: Presto Mobile

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  get_it: ^5.0.3
  provider: ^4.3.2+3
  google_fonts: ^1.1.1
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  simple_animations: ^2.1.0
  fluttertoast: ^7.1.1
  intro_slider: ^2.3.3
  firebase_messaging: ^7.0.3
  progress_indicators: ^0.1.5
  google_maps_flutter: ^0.5.31
  geolocator: ^5.3.1
  platform_device_id: ^0.1.1
  permission_handler: ^5.0.1+1
  countdown_flutter: ^0.1.2
  numberpicker: ^1.2.0
  connectivity: ^2.0.1
  firebase_analytics: ^5.0.11
  firebase_core: ^0.5.3
  stacked: ^1.7.7
  shared_preferences: ^0.5.12+4
  share: ^0.6.5+4
  file_picker: ^2.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
